### ISSUE TITLE
FUNCALLF and APPLYF are not implemented

### ISSUE THREAD

**Issue by phoe** [Hexstream/place-utils#1]
https://github.com/Hexstream/place-utils/blob/cbfc5e3de274f60a99066cb6768912623f0c3d1e/package.lisp#L9-L10

I have not seen the implementations for those operators anywhere in the codebase, but their names are exported and they seem to be documented.

**Comment by Hexstream** [comment]
Thank you. `funcallf` and `applyf` have been obsoleted by [place-modifiers](https://www.hexstreamsoft.com/libraries/place-modifiers/) ages ago.
It effectively provides hundreds of modify macros, including `(modify funcall)` and `(modify apply)`.
